{% set name = "oslo.context" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75a9a722a552fba8a89e8a01028fa82a6190ab317a9591bb83303a2210a79144

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - pip
  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - debtcollector >=1.2.0

test:
  imports:
    - oslo_context

about:
  home: https://docs.openstack.org/oslo.context/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The Oslo context library has helpers to maintain useful information about a request context.
  dev_url: https://docs.openstack.org/infra/manual/developers.html

extra:
  recipe-maintainers:
    - tschoonj
