{% set name = "oslo.context" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f578ea38569cf0a677e2167178196b21a54175471358c4320ddfd5c97c52f4d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - pip
  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - debtcollector >=1.2.0

test:
  imports:
    - oslo_context

about:
  home: https://docs.openstack.org/oslo.context/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The Oslo context library has helpers to maintain useful information about a request context.
  dev_url: https://docs.openstack.org/infra/manual/developers.html

extra:
  recipe-maintainers:
    - tschoonj
